src/objects/Time_Sheet_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Timesheet Activities</relationshipLabel>
        <relationshipName>Timesheet_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client Facing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Client Facing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fri__c</fullName>
        <label>Fri</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mon__c</fullName>
        <label>Mon</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Timesheet Activities</relationshipLabel>
        <relationshipName>Timesheet_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sat__c</fullName>
        <label>Sat</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Activity_Type__c</fullName>
        <label>Sub-Activity Type</label>
        <picklist>
            <controllingField>Activity_Type__c</controllingField>
            <picklistValues>
                <fullName>Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trouble Shooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Displacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Training/workshop/seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal emails</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRUST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Tech issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal follow ups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sun__c</fullName>
        <label>Sun</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thur__c</fullName>
        <label>Thur</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Activities</relationshipLabel>
        <relationshipName>Timesheet_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tue__c</fullName>
        <label>Tue</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wed__c</fullName>
        <label>Wed</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Timesheet Activity</label>
    <nameField>
        <displayFormat>TSI-{00000}{YYYY}</displayFormat>
        <label>Time Sheet Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Week_Commencing__c</fullName>
        <label>Week Commencing</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS{00000}-{YYYY}</displayFormat>
        <label>Timesheet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchGenerateTimesheets.cls
global class BatchGenerateTimesheets implements Database.Batchable<sObject>{

    global string query = 'SELECT Id,Name from User where Time_Study_User__c = TRUE and isActive = TRUE';

    map<Id, List<Task>> userTaskMap; 
    map<Id, List<Event>> userEventMap;
    map<Id, Timesheet__c> timesheetMap;
    map<string,Time_Sheet_Activity__c> activityMap;
    
    // do I need this??
    List<Timesheet__c> insertTimesheetList;
    
    
    DateTime startDate;
    DateTime endDate; 
    Date baseMonday = date.newInstance(1900,1,8);   

    global BatchGenerateTimesheets() {
        // check if I'm a monday
        if(Math.MOD(baseMonday.daysBetween(Date.Today()),7) == 0) {
            system.debug('its monday');
        } else {
            // throw an error
        }
        
        startDate = Datetime.newInstance(Date.today(), Time.newInstance(0,0,0,0));
        endDate = DateTime.newInstance(startDate.addDays(7).date(), Time.newInstance(23,59,59,59));
    }
    
    global BatchGenerateTimesheets(Date runDate) {
        startDate = Datetime.newInstance(runDate, Time.newInstance(0,0,0,0));
        endDate = DateTime.newInstance(startDate.addDays(7).date(), Time.newInstance(23,59,59,59));
    }         


    global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<sObject> scope) {

        // TODO:: wrap this in a big try-catch

        prepare(scope);        


///////  map over each user and create the timesheets;

        for(User each : (List<User>)scope) {
            // check if there's a timesheet
            if(timesheetMap.containsKey(each.Id) == FALSE) {
                Timesheet__c ts = new Timesheet__c();
                ts.OwnerId = each.id;
                ts.week_commencing__c = startDate.date();
                timesheetMap.put(each.Id, ts);
                
           } 
 
            
        }
        upsert timesheetMap.values();



        for(Timesheet__c eachTimesheet : timeSheetMap.values()) {
            // populate the timesheet activities

            if(userTaskMap.containsKey(eachTimesheet.OwnerId)) {           
                for (Task eachTask : userTaskMap.get(eachTimesheet.OwnerId)) {
                    string mapkey = eachTask.Type + eachTask.OwnerId + eachTask.Account.tfCrmCountry__c + eachTask.Account.Id + eachTask.Product_Family_A_M__c;
                    if(activityMap.containsKey(mapkey)) {
                        Time_Sheet_Activity__c activity = activityMap.get(mapkey);
                        // what to do here??
                        activity.Mon__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 0)    ? activity.Mon__c + 1 :activity.Mon__c;
                        activity.Mon__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 1)    ? activity.Tue__c + 1 :activity.Tue__c;
                        activity.Wed__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 2)    ? activity.Wed__c + 1 :activity.Wed__c;
                        activity.Thur__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 3)   ? activity.Thur__c + 1 :activity.Thur__c;
                        activity.Fri__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 4)    ? activity.Fri__c + 1 :activity.Fri__c;
                        activity.Sat__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 5)    ? activity.Sat__c + 1 :activity.Sat__c;
                        activity.Sun__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 6)    ? activity.Sun__c + 1 :activity.Sun__c;
    
                    } else {
                        Time_Sheet_Activity__c activity = new Time_Sheet_Activity__c(Timesheet__c = eachTimesheet.Id);
                        activity.Country__c = eachTask.Account.tfCrmCountry__c;
                        activity.Account__c = eachTask.Account.Id;
                        activity.Activity_Type__c = (eachTask.Type == 'Internal Activity') ? 'Non-Client Facing':'Client Facing';
                        activity.Sub_Activity_Type__c = eachTask.Type;
                        activity.Product__c = eachTask.Product_Family_A_M__c;
                        activity.Mon__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 0)    ? 1 :0;
                        activity.Tue__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 1)    ? 1 :0;
                        activity.Wed__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 2)    ? 1 :0;
                        activity.Thur__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 3)   ? 1 :0;
                        activity.Fri__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 4)    ? 1 :0;
                        activity.Sat__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 5)    ? 1 :0;
                        activity.Sun__c = (baseMonday.daysBetween(eachTask.ActivityDate) == 6)    ? 1 :0;
 
                         // put it in the map
                        activityMap.put(mapkey,activity);
                    }
                    
                    // tie it to the timesheet
                    eachTask.Timesheet__c = eachTimesheet.Id;            
                
                }
            
            }
            
            //look for events and tie them to days
            //look for tasks and tie them to days
            // do whatever to dedupe
          
            
            
        }


    }


    global void finish(Database.BatchableContext bc) {
    
    }

    void prepare(List<SObject> scope) {
        userTaskMap = new map<Id, List<Task>>();
        for(Task eachTask : [select Id, ownerId, ActivityDate, Account.Id, Type, Product_Family_A_M__c,Account.tfCrmCountry__c from Task where ownerId in :scope AND createddate >= :startDate and createddate <= :endDate and Timesheet__c = null]) {
            if (userTaskMap.containsKey(eachTask.ownerId) == FALSE) {
                userTaskMap.put(eachTask.ownerId, new List<Task> {eachTask});
            } else {
                userTaskMap.get(eachTask.ownerId).add(eachTask);
            }
        }

        userEventMap = new map<Id, List<Event>>();
        for(Event eachEvent : [select Id, ownerId, Account.Id, Type, Product_Family_A_M__c,Account.tfCrmCountry__c from Event where ownerId in :scope AND createddate >= :startDate and createddate <= :endDate and Timesheet__c = null]) {
            if (userEventMap.containsKey(eachEvent.ownerId) == FALSE) {
                userEventMap.put(eachEvent.ownerId, new List<Event> {eachEvent});
            } else {
                userEventMap.get(eachEvent.ownerId).add(eachEvent);
            }
        }    
        

        timeSheetMap = new map<Id,Timesheet__c>();
        for(Timesheet__c eachTimesheet : [select Id, OwnerId from Timesheet__c where ownerId in :scope AND Week_Commencing__c >= :startDate.Date() AND Week_Commencing__c <= :endDate.Date()]) {
            timesheetMap.put(eachTimesheet.OwnerId, eachTimesheet);
        }    
    
    }

    
    
}