src/objects/Time_Sheet_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Timesheet Activities</relationshipLabel>
        <relationshipName>Timesheet_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client Facing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Client Facing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fri__c</fullName>
        <label>Fri</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Industry_Class__c</fullName>
        <label>Industry Class</label>
        <picklist>
            <picklistValues>
                <fullName>Equities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit &amp; Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commodities &amp; Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mon__c</fullName>
        <label>Mon</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Timesheet Activities</relationshipLabel>
        <relationshipName>Timesheet_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sat__c</fullName>
        <label>Sat</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Activity_Type__c</fullName>
        <label>Sub-Activity Type</label>
        <picklist>
            <controllingField>Activity_Type__c</controllingField>
            <picklistValues>
                <fullName>Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trouble Shooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Displacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Training/workshop/seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal emails</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRUST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Tech issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal follow ups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sun__c</fullName>
        <label>Sun</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thur__c</fullName>
        <label>Thur</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Activities</relationshipLabel>
        <relationshipName>Timesheet_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Line_Activity__c</fullName>
        <formula>Mon__c +  Tue__c + Wed__c + Thur__c + Fri__c + Sat__c + Sun__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Line Activity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tue__c</fullName>
        <label>Tue</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wed__c</fullName>
        <label>Wed</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Timesheet Activity</label>
    <nameField>
        <displayFormat>TSI-{00000}{YYYY}</displayFormat>
        <label>Time Sheet Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS{00000}-{YYYY}</displayFormat>
        <label>Timesheet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimesheetController.cls
public with sharing class TimesheetController {

    public Timesheet__c timesheet {get; set;}
    public List<TSWrapper> activityList;
    public List<Time_Sheet_Activity__c> deleteList {get; set;}
    
    
    public TimesheetController(ApexPages.StandardController controller) {
        controller.addfields(new list<string>{'Status__c'});
        this.timesheet = (Timesheet__c)controller.getRecord();
        
    }

    public List<TSWrapper> getActivityList() {
        deleteList = new List<Time_Sheet_Activity__c>();
        if (activityList == null) {
            activityList = new List<TSWrapper>();
            for (Time_Sheet_Activity__c eachActivity : [select name, Activity_Type__c, Country__c, Fri__c, Industry_Class__c, Account__c,
            Mon__c, Product__c, Sat__c, Sun__c, Thur__c, Tue__c, Wed__c, Total_Line_Activity__c,Sub_Activity_Type__c
              from Time_Sheet_Activity__c
              where Timesheet__c = :this.timesheet.Id]) {
                  activityList.add(new TSWrapper(eachActivity, activityList.size()));
              }
            

        }
        if (activityList.size() == 0) {
            activityList.add(new TSWrapper(addActivity(), activityList.size()));
        }
        
        return activityList;
    }

    public PageReference addRow() {
        activityList.add(new TSWrapper(addActivity(), activityList.size()));
        return null;
    }

    public Pagereference deleteRow() {
        // activityList.add(addActivity());
        return null;
    }

    private Time_Sheet_Activity__c addActivity() {
        Time_Sheet_Activity__c tsa = new Time_Sheet_Activity__c(timesheet__c = timesheet.Id,
            mon__c=0, tue__c=0,wed__c=0,thur__c=0,fri__c=0,sat__c=0,sun__c=0);
        return tsa;
    }



    public PageReference saveAll() {
        try {
            upsert timesheet;
            // remove nulls
            
            List<Time_Sheet_Activity__c> upsertList = new List<Time_Sheet_Activity__c>();
            // List<Time_Sheet_Activity__c> deleteList = new List<Time_Sheet_Activity__c>();
            
            for (TSWrapper wrapper : activityList) {
                if(wrapper.del != true  && sumHours(wrapper.rec) > 0 && wrapper.rec.account__c != null) {
                    upsertList.add(wrapper.rec);
                } else if (wrapper.rec.Id != null) {
                    deleteList.add(wrapper.rec);
                }
            
            }
            upsert upsertList;
            delete deleteList;
            getActivityList();

            PageReference tsPage = new ApexPages.StandardController(timesheet).edit();
            tsPage.setRedirect(true);
            return tsPage;


        } catch (Exception e) {           
            system.debug(e);
            return null;
        }

    }
    
    public Class TsWrapper {
        public boolean del {get; set;}
        public Integer num {get; set;}
        public Time_Sheet_Activity__c rec {get; set;}
        
        public TsWrapper(Time_Sheet_Activity__c rec, Integer num) {
            del = false;
            this.rec = rec;
            this.num = num;
        }
    
    
    }
    
    
    private Decimal sumHours (Time_Sheet_Activity__c tsa) {
        return ifnull(tsa.mon__c) + ifnull(tsa.tue__c) + ifnull(tsa.wed__c) 
            + ifnull(tsa.thur__c) + ifnull(tsa.fri__c) + ifnull(tsa.sat__c) + ifnull(tsa.sun__c);
 
    }

    private Decimal ifnull(Decimal integ) {
        return (integ == null) ? 0 : integ; 
    }    
}